spring:
  application:
    name: questionnaire-backend
  datasource:
    url: jdbc:mysql://localhost:3306/questionnaire?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: questionnaire
    password: 8RbJFp3b2ZM6fYYe
  session:
    timeout: 86400
    store-type: redis
  config:
    activate:
      on-profile: prod
  redis:
    port: 6379
    host: localhost
    database: 4
    timeout: 60000

server:
  port: 8102
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)